#+TITLE: Joy的学习笔记
#+DATE: <2018-01-13 Sat 17:07>
#+Author: NewJoy
#+TAGS: Tensorflow, CNN, Action Detection
#+LAYOUT: post
#+CATEGORIES: Joy

* problems
  1. occluded keypoints
  2. invisible keypoints 
  3. complex background

* papers

  1. Action Recognition from a Distributed Representation of Pose and Appearance, CVPR,2010
  2. Combining Randomization and Discrimination for Fine-Grained Image Categorization, CVPR,2011
  3. Object and Action Classification with Latent Variables, BMVC, 2011
  4. Human Action Recognition by Learning Bases of Action Attributes and Parts, ICCV, 2011
  5. Learning person-object interactions for action recognition in still images, NIPS, 2011
  6. Weakly Supervised Learning of Interactions between Humans and Objects, PAMI, 2012
  7. Discriminative Spatial Saliency for Image Classification, CVPR, 2012
  8. Expanded Parts Model for Human Attribute and Action Recognition in Still Images, CVPR, 2013
  9. Coloring Action Recognition in Still Images, IJCV, 2013
  10. Semantic Pyramids for Gender and Action Recognition, TIP, 2014
  11. Actions and Attributes from Wholes and Parts, arXiv, 2015
  12. Contextual Action Recognition with R*CNN, arXiv, 2015
  13. Recognizing Actions Through Action-Specific Person Detection, TIP, 2015

* Progress

** Pre intro
   
   Inspired by this [[https://adeshpande3.github.io/adeshpande3.github.io/The-9-Deep-Learning-Papers-You-Need-To-Know-About.html][blog on DL]], it provides some intuitive insights

*** More resources
    https://cs231n.github.io/convolutional-networks/

** Intro to Convolutional Neural Networks
   Following the guide in this url
   https://www.tensorflow.org/tutorials/layers

   Heads up: there are 3 layers to build, learn with caution.

*** Convolutional layers
    虽然全连接层也可以用来学习和分类(fully connected feedforward neuron networks), 但是由于小的图片也会导致很多的参数需要训练. 如(100x100)=10000, 基本是$O(n^2)$. 采用卷积神经网络可以实现降维, 使得快速的训练成为可能. 使得网络更深更少参数.
**** Filters
     虽然不是纯数学上的卷积。简单来看就是
**** Activation function
     In computational networks, the activation function of a node defines the output of that node given an input or set of inputs.

     在计算网络里面，一个节点根据一个或多个输入作出的输出定义为激活函数。
*** Pooling Layers

*** Dense(fully connected) layers

** Papers
